title: DACE-DL
description: Official DACE-DL project page

url: https://DACE-DL.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
#plugins: [jekyll-paginate]
#paginate: 5

plugins: [jekyll-paginate-v2]

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
# The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/news/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.


navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: News
    url: /news
  - title: Partnership
    url: /partnership
  - title: Contact
    url: /contact
  - title: Download
    url: /download

social:
  github: 
  twitter: 
  facebook:
  email: 
  linkedin: 

google_analytics: 

disqus:
    shortname: dace-dl
