title: DACE-DL
description: DACE-DL ANR project homepage

url: https://dace-dl.github.io
paginate_path: "news/page:num/"
permalink: news/:title/ lpto/



# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
#  - title: News
#   url: /news/index.html
  - title: Partners
    url: /partners
  - title: Contact
    url: /contact
  - title: Results
    url: /results

social:
  github: https://github.com/DACE-DL
  twitter: 
  facebook:
  email: konstantin.Todorov@lirmm.fr
  linkedin: 

google_analytics: 

disqus:
    shortname: dace-dl
