title: DACE-DL
description: Official DACE-DL project page

url: https://DACE-DL.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: 
  twitter: 
  facebook:
  email: raphael.conde-salazar@inrae.fr
  linkedin: 

google_analytics: 

disqus:
    shortname: raphaël
