title: DACE-DL
description: Official DACE-DL project page

url: https://DACE-DL.github.io
paginate_path: "news/page:num/"
permalink: news/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: News
    url: /news/index.html
  - title: Partnership
    url: /partnership
  - title: Contact
    url: /contact
  - title: Download
    url: /download

social:
  github: 
  twitter: 
  facebook:
  email: 
  linkedin: 

google_analytics: 

disqus:
    shortname: dace-dl
